### PR TITLE
love confession

### PR DESCRIPTION
**Pull request by SeniorMars**

### CODE REVIEW

**Comment by wishawa** [comment]
Please properly escape "<" character as per HTML standard 😡😡😡

**Comment by SeniorMars** [comment]
No

**Comment by SeniorMars** [comment]
fine only for you

**Comment by wishawa** [comment]
this is incorrect

**Comment by SeniorMars** [comment]
heck.

**Comment by wishawa** [comment]
https://stackoverflow.com/questions/42182/how-to-escape-and-inside-pre-tags

**Comment by SeniorMars** [comment]
fixed in new PR. merge i need my hacktober fest shirt fr fr on g

**Comment by Alex-Janssen** [comment]
This is highly unprofessional.  Please leave pull requests for serious matters.

**Comment by SeniorMars** [comment]
This is a serious matter. I'm in love.

**Comment by SeniorMars** [comment]
reopen this

**Comment by Alex-Janssen** [comment]
@SeniorMars Report for harassment.

**Pull request closed without merging**
